### PR TITLE
Laravel 11.x Compatibility

### PR DESCRIPTION
**Pull request by laravel-shift**
This is an automated pull request from [Shift](https://laravelshift.com) to update your package code and dependencies to be compatible with Laravel 11.x.

**Before merging**, you need to:

- Checkout the `l11-compatibility` branch
- Review **all** comments for additional changes
- Thoroughly test your package

If you do find an issue, please report it by commenting on this PR to help improve future automation.

### CODE REVIEW

**Comment by laravel-shift** [comment]
:warning: The latest version of Laravel has a dependency for `phpunit/phpunit` of `^10.5`. If you would like to also upgrade your tests, you may run the [PHPUnit 10 Shift](https://laravelshift.com/upgrade-phpunit-10) for free.

**Comment by laravel-shift** [comment]
:alembic: **Using this package?** If you would like to help test these changes or believe them to be compatible, you may update your project to reference this branch.

To do so, temporarily add Shift's fork to the `repositories` property of your `composer.json`:

```json
{
    "repositories": [
        {
            "type": "vcs",
            "url": "https://github.com/laravel-shift/laravel-mail-css-inliner.git"
        }
    ]
}
```

Then update your dependency constraint to reference this branch:

```json
{
    "require": {
        "fedeisas/laravel-mail-css-inliner": "dev-l11-compatibility",
    }
}
```

Finally, run: `composer update`

**Comment by TSchuermans** [comment]
@DannyvdSluijs I might be wrong, but it seems that the CI is only triggered on the master branch.
Seeing as the branch is called l11-compatibility might explain this.

**Comment by DannyvdSluijs** [comment]
@TSchuermans I've taken a look and the same issue also applies to https://github.com/fedeisas/laravel-mail-css-inliner/pull/316. But then https://github.com/fedeisas/laravel-mail-css-inliner/pull/308 shows it has worked before. 

I've created and merged https://github.com/fedeisas/laravel-mail-css-inliner/pull/323 in order to bring the workflow to a updated state.

Now [linting](https://rhysd.github.io/actionlint/#eJy9VttO3DAQfd+vGCGkpQhnubRSFakIFanAQ1Wksk9VtXKSycbg2Kkvy038e8cxm72wUASFvOzGHh+fOTNzFMVrTOHwpNfTKu0BNN5W4RcgM1zlFdoUfkHNrUMDv9sAKUcG/3i07onA3rnObNh3XZxqrzo9PoX121uKdEZcJWER7u7aAOOVZUQDfOaV80zycLjdss7Qy/g6IgGUXEhW0mUp/ZUW75cj6DQIQKhc+gJnCwAMmqpJ4XOyPbcIwKXUl6MAu4gYn0i9H7jTQbgUroLIDgpsbP9N8PVlwLeOZxIfXAOQ67rRFs3INwVRGZWSj6kGfcYagyUadg/QvUeklVx3Xsp153lavBr/HbXYfSnX3edp8Wr8d9Ri76Vc956nxavx31ILcrLGTq2DgbfB4njuhFZ2QIaXX2jvDiYfe11IpPgTnW+WfY4SntpceCKYrcSE1xRReTOw4RijuIPJrEVClvPuRdtsgsaKYJOPwwPglUMVwuiaQtdbIEV2VcstqDPyUqHGW2SOjt7bxVJIFKrUW3AjmjmUXNNlfExJXRWY+fFyqkfoOo0h5yQKFMJg7rS5nplwkXZBrA3qtsjxU8C80rBG576sb8zAtCrFOGKyQM8yiviwBvv7sH50cnY8/Dr6MTw7HZ4tczqMNLBBVaDKBdol1bsShsBQv0fFpsJEldtWSBaTSKj6jXc2IV6L2l/gdTxG6Sk0iba0z7rTYafitvoWstrob24OplvJudWq/2ERzVCDaoOMUO1TsMs6nChqZilXK9EK34kt7kO7MShEOxRKM05NFP9Ru1AvtNrFhcboMZGz9KYbJ2pxg4x7p6XmBZplOsN2AlezEWU6beSVE/sI7RgyPwYrTwc5V4+o0TTsNXznjuppLJTahLkdKuFWtWia8qJgdYxO07lSOK3lKPb/3d2AhtETRFvNtQ6IOtoJ5ZG+cBgao83CAM+8bwXds+BRreHdQy+ym5Ci2gwyoaZXU0mmo8scWcH/IHEYHK+VaOIlJc0zIYV7vKks5t4Id81aq6SGeCGHrsGVNjWX1GXpv78Wn+ncSxlOqXc3LTmH1DmXFTnlzeAhKxYvONhOPiW7fwEvTWIP) shows no errors anymore

**Review by DannyvdSluijs — APPROVED** [review]

**Pull request merged**
