### PR TITLE
Add Laravel v7 support

### PR DESCRIPTION
**Pull request by introwit**
Please tag a release soon :)

### CODE REVIEW

**Comment by zupolgec** [comment]
This is not enough. In Laravel 7 something changed about Mailers.

I managed to have it working changing these lines in LaravelMailCssInlinerServiceProvider.php from this:
```
$this->app->extend('swift.mailer', function (Swift_Mailer $swiftMailer, $app) {
    $inlinerPlugin = $app->make(CssInlinerPlugin::class);
    $swiftMailer->registerPlugin($inlinerPlugin);
    return $swiftMailer;
});
```

to:
```
$this->app->extend('mail.manager', function (MailManager $mailManager) {
    $mailManager->getSwiftMailer()->registerPlugin($this->app->make(CssInlinerPlugin::class));
    return $mailManager;
});
```

But this change should be on a new version branch, compatible only with Laravel 7.

**Comment by introwit** [comment]
@zupolgec nothing has changed with regards to the scope of this package. Only the structure of the `config/mail.php` file has been changed ([upgrade notes](https://laravel.com/docs/7.x/upgrade)) but that is not related to this package in anyway, something else might be broken in your laravel 7 app. @fedeisas can we merge this PR and tag a major release for Laravel 7 please? 🙂

**Comment by zupolgec** [comment]
@introwit did you test it? I did. Brand new Laravel 7 app and it doesn't work.

The initialization of Switft Mailer changed: https://github.com/laravel/framework/commit/53f555a74cf3d02715b1a4bf7c2a4ac125beab13#diff-47a7eab8d5efdc88be216b16d303c993

If you need a fixed package, add these lines at the end of your composer.json file:
```
"repositories": [
    {
        "type": "vcs",
        "url": "https://github.com/zupolgec/laravel-mail-css-inliner.git"
    }
]
```

and add `"fedeisas/laravel-mail-css-inliner": "dev-master"` in the require section.

**Comment by timhaak** [comment]
@zupolgec possibly create a pull request with your changes as well to make it easier for the maintainer to merge :).

Thanks for working it out what was needed :)

**Pull request merged**
