### PR TITLE
Update css-to-inline-styles to v2.1

### PR DESCRIPTION
**Pull request by Belphemur**
Update the test, remove the configuration that are not used anymore
Add config to set CSS files to be use directly in emails

### CODE REVIEW

**Comment by ceesvanegmond** [comment]
@Belphemur Thank you for the addition! Why doesn't it pass on HHVM? Could you fix that?

**Comment by Belphemur** [comment]
It's the library itself, not the code here.

@tijsverkoyen has put HHVM as allow_failure on his test for now. You can see it here in the last build: https://travis-ci.org/tijsverkoyen/CssToInlineStyles/jobs/160315806

I can't do anything about this other than also asking travis to allow the failure.

**Comment by ceesvanegmond** [comment]
@Belphemur Could you add the 
```yaml
  allow_failures:
    - php: hhvm
```

to this merge request too?

**Comment by Belphemur** [comment]
@ceesvanegmond added :+1:

**Comment by ceesvanegmond** [comment]
@Belphemur Thx!

**Comment by ceesvanegmond** [comment]
@Belphemur Is this fully backwards compatible? Should we tag it on v1.6?

**Comment by Belphemur** [comment]
I would bump the major version since the behavior of the lines also changed. It doesn't strip the style tag anymore. 

Moreover the default config changed to add the possibility to set the css files and removed the other options.

**Comment by ceesvanegmond** [comment]
@Belphemur Right! Check it out!
https://github.com/fedeisas/laravel-mail-css-inliner/releases/tag/2.0

**Comment by Belphemur** [comment]
@ceesvanegmond Cheers!

Thanks for the quick update.

**Pull request merged**
