### PR TITLE
Laravel 7 compatibility

### PR DESCRIPTION
**Pull request by zupolgec**
See issue https://github.com/fedeisas/laravel-mail-css-inliner/pull/70

### CODE REVIEW

**Comment by zupolgec** [comment]
Breaks backward compatibility with Laravel 5 and 6

**Comment by vesper8** [comment]
@zupolgec if the changes made in src/LaravelMailCssInlinerServiceProvider.php  only work on Laravel 7, then the composer.json should now only support `^7.0` in a new tagged release? By adding `^5.0|^6.0|^7.0` won't that cause problems with people who don't have L7?

**Comment by zupolgec** [comment]
@vesper8 yep, you're right! thanks 😉

**Comment by vesper8** [comment]
possible to merge this one pretty please @fedeisas ?

**Comment by jdavidbakr** [comment]
@zupolgec - maybe update the travis.yml to exclude the irrelevant versions of PHP to at least get Travis happy

**Comment by duxthefux** [comment]
would be really cool to merge this soon

**Comment by jdavidbakr** [comment]
Any chance we can get an update on when this might get merged it?  This is the only package that is preventing me from upgrading my projects to Laravel 7.

**Comment by djereg** [comment]
@jdavidbakr metoo :)

@fedeisas I'm looking forward to get notification about new release.

**Comment by zupolgec** [comment]
@jdavidbakr @djereg you can use my repository for the time being. See https://github.com/fedeisas/laravel-mail-css-inliner/pull/70#issuecomment-594754639

**Pull request merged**
