### PR TITLE
Add Support for Laravel 9

### PR DESCRIPTION
**Pull request by QusaiFarraj**
This PR will add support for Laravel 9.

I ran the test within the repo after the upgrade and all passed.

### CODE REVIEW

**Comment by shawkiIIalasy** [comment]
@sietzekeuning Please check

**Comment by ajohnson6494** [comment]
This will not work as SwiftMailer is no longer used by Laravel. Need to update to Symfony Mailer. See PR #173

**Comment by QusaiFarraj** [comment]
Im closing this PR in favor of #173

**Comment by mahmoudAkobah** [comment]
@sietzekeuning   Could you please let me know when  will upload a release contain this PR

**Comment by sietzekeuning** [comment]
@mahmoudAkobah I don't have control over this repository, so you will need to ask the owner

**Pull request closed without merging**
